# -*- coding: utf-8 -*-
"""rf-spectrum-classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ft9esnJsOO-jqnIa5oXeAigWhtsMd6oW
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import joblib

# Simulated dataset
data = {
    'frequency_mhz': [1200, 1500, 2500, 3500, 7000, 10000, 18000],
    'bandwidth_mhz': [20, 25, 30, 40, 50, 60, 80],
    'power_dbm': [-10, -5, 0, 5, 10, 15, 20],
    'modulation': ['BPSK', 'QPSK', 'QAM16', 'QAM64', 'BPSK', 'QPSK', 'QAM16'],
    'spectrum_band': ['L', 'L', 'S', 'C', 'X', 'Ku', 'Ka']
}

df = pd.DataFrame(data)

# Encode categorical feature
le = LabelEncoder()
df['modulation_encoded'] = le.fit_transform(df['modulation'])

# Features and labels
X = df[['frequency_mhz', 'bandwidth_mhz', 'power_dbm', 'modulation_encoded']]
y = df['spectrum_band']

# Train model
model = RandomForestClassifier()
model.fit(X, y)

# Save model and encoder
#joblib.dump(model, 'model.pkl')
#joblib.dump(le, 'label_encoder.pkl')
#print("Model and encoder saved.")